spring:
  profiles:
    active: ${SPRING_PROFILE:dev}
  application:
    name: financeiro
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8080

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /docs
    oauth:
      client-id: financeiro-frontend
      use-pkce-with-authorization-code-grant: true
      scopes: "openid profile email"

brapi:
  url: https://brapi.dev
  token: ${BRAPI_TOKEN:}
